### ISSUE TITLE
Customize tags in jsonToXml function

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [javadev/xml-to-json#1]
Hi!

The library works fine, but I was wondering If it's possible to customize ```<root>``` and ```<element>``` tags in jsonToXml function.

For instance, i'd like to call

jsonToXml(data, "cars","owned_car")

in order to generate the following xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<cars>
  <owned_car>
    .....
 </owned_car>
<owned_car>
    .....
 </owned_car>
</cars>
```

**Comment by javadev** [comment]
Hi!

I added `<root>` and `<element>` tags in jsonToXml function.

Have a nice day!
